benhoyt/inih

cpp/INIReader.cpp
added an validated solution to replace std::map::at method, which is not available until c++11.
=> Update INIReader.cpp file

cpp/INIReader.cpp, cpp/INIReader.h
Hello.
I propose to change argument types from direct type to constant reference so it will be good from performance side as string do not copy at method call.
Get method also can return constant reference so no temporary string will not be provided, it copy already to string that expected to take data from Get method.
Thank you.
P.S.
By the way, if you interesting about other change that can be provide for this class (most expected that compiler support C++ 11) I save my view at [separate branch](https://github.com/TheVice/inih/tree/vicemaster) at repository fork.
=> [INIReader] class now using constant reference as method arguments.

ini.c
This pull request fixes -Wstringop-truncation (implemented in GCC 8.1), without changing the behavior of the function.
=> Silence -Wstringop-truncation

ini.c
This avoids this error and warning in cppcheck:
```
[ini.c:92]: (style) The scope of the variable 'offset' can be reduced.
[ini.c:127]: (error) Deallocation of an auto-variable results in undefined behaviour.
```
We don't need to free 'line' if we're using the stack. This also avoids problems if the user misconfigures their inih options by setting INI_ALLOW_REALLOC while using the stack, which as ini.h says "Only applies if INI_USE_STACK is zero."
=> Avoid cppcheck free() error

cpp/INIReader.cpp, cpp/INIReader.h
Same as `INIReader::Get`, but returns `default_value` if the value is an empty string, which provides functionality similar to `GetInteger` and the others.
I'm not sure about the function name (implies that `Get` is something else?), but I definitely don't want to change the behavior of `Get` and I also think this functionality is really needed. `GetString` is the best name I could come up with that isn't overly convoluted (e.g. I ruled out `GetButIfValueIsEmptyStringThenReturnDefaultValueInstead`) and I don't think it'll cause anyone trouble.
=> Add INIReader::GetString to get nicer default_value behavior

README.md, ini.c, tests/baseline_call_handler_on_new_section.txt, tests/baseline_disallow_inline_comments.txt, tests/baseline_handler_lineno.txt, tests/baseline_heap.txt, tests/baseline_heap_realloc.txt, tests/baseline_heap_realloc_max_line.txt, tests/baseline_multi.txt, tests/baseline_multi_max_line.txt, tests/baseline_single.txt, tests/baseline_stop_on_first_error.txt, tests/duplicate_sections.ini, tests/unittest.bat, tests/unittest.c, tests/unittest.sh
Some programs have ini files with multiple sections that have the same name, which would make it very useful to know when a new section is encountered.
This patch adds this ability as an option that's enabled by setting INI_CALL_HANDLER_ON_NEW_SECTION to 1.
When enabled, the handler callback can check the name parameter. If it's NULL, then it was called because a new section was entered.
=> Add option to call handler when a new section is encountered

cpp/INIReader.cpp, cpp/INIReader.h, ini.c, ini.h
Afaiui inih is not shipped as a shared library but is designed for copying the relevant files to inih-using project's sources.  Especially for this use-case it is very helpful to have proper attribution and clear, accessible information about the applicable license terms _in each file_.
This merge request adds
a) a copyright statement and
b) an SPDX id  https://spdx.org/ids to have in-file license information.
Thanks for considering!
=> 2019 07 add copyright and spdx

ini.h
(And disabled by default)
This slipped through the cracks in #79 ;).
Fixes a harmless `-Wundef` warning:
```
inih/ini.c: In function 'ini_parse_stream':
inih/ini.c:169:5: warning: "INI_CALL_HANDLER_ON_NEW_SECTION" is not defined, evaluates to 0 [-Wundef]
#if INI_CALL_HANDLER_ON_NEW_SECTION
```
=> Make sure INI_CALL_HANDLER_ON_NEW_SECTION is defined

ini.c, ini.h
This fixes compile failures with the strict compiler flags, please see below.
It's to see, that `(ini_reader)fgets` is actually used as reader, which actually uses int. Still, it is done as an explicit cast. The surrounding errors reported by the compiler are about `strlen` result assigned to an int var, and int var passed to realloc. An enhancement to this might be to additionally write a wrapper around fgets, which would use `size_t` in the signature. 
Another way to solve this would be to keep ints, and do explicit casts. IMO size_t is a better solution, for both type safety and security.
Finally, i'm not sure how bad it is to break the existing API, but from the usability perspective this should be fixed one or another way.
Thanks.
```
inih/ini.c: In function ‘ini_parse_stream’: …
```
=> Fix possible int overflow in reader cb

meson.build
I don't know if you are interested considering #59, but I wired up meson support anyway. This is purely optional for users, but a nice feature for distros that want to ship your parser.
The specific reason for this is Feral's gamemode, which ship its own (old) version of inih but rather should use a system installation which is easy to link against.
Installing via meson adds `ini.h` to the include path, adds a shared library `libinih.so` which programs can dynamically link against and also adds a pkg-config entry, so programs can find it.
The nice thing about meson is that you don't have to care about any paths, just change the project version for a new release, and in case there is a breaking API change bump the `soversion`.
In case you don't want to change the build file for every …
=> add meson for system install

meson.build
Using include directories instead of adding the headers to the source properly accounts for the right dependencies. This is mainly if you want to do this:
```C
#include <ini.h>
```
Which would fail if inih isn't installed on the system.
=> meson: use include directories

README.md, meson.build, meson_options.txt
With this PR I want to add the possibility to _either_ install inih as a shared library _or_ to just build it as a static library. Installing it by default causes some minor inconveniences for some downstream users, so making it optional seems a good idea. I also sneaked in two minor commits.
WiP since I currently only implemented the installation option.
Is it okay to mark this as r49 once implemented? Would get it faster to downstream users.
/cc @kakra, ref FeralInteractive/gamemode#222.
=> Add options for Meson

meson.build
Isn't really needed and only bloats the commit history (if bumped for every release) for this small lib.
=> meson: remove project version

meson.build
Meson doesn't have a `str` function, so it's not possible to change the integer options.
`subprojects/inih/meson.build:50:8: ERROR: Unknown function "str".`
=> Meson: fix the integer conversions

README.md, meson.build, meson_options.txt
inih as a shared library becomes increasingly popular and is even used by xfsprogs now. Because of that, I think it's a good idea to enable these settings in Meson by default. Since Meson supports individual settings per subproject, this won't break any use case.
I also added a small note so that issues like #123 don't appear again.
=> enable distro settings by default

meson.build
Just noticed a small bug, when setting static compile commands in Meson, they haven't been applied to objects that depend on it. Since this might created some bugs, it would be cool if you could tag this a new release (even though no code changed since r52).
=> meson: add static compile args to inih_dep

cpp/INIReader.h, ini.h, meson.build
They are required to properly build DLLs on Windows, and improve the quality of shared objects on Linux. See https://gcc.gnu.org/wiki/Visibility for details.
This issue was first discovered here: https://github.com/mesonbuild/wrapdb/pull/340#issuecomment-1075102565
CC @stephanlachnit and @eli-schwartz
=> Add visibility symbols

meson.build
Otherwise, the installed .pc file contains "Version: undefined".
Signed-off-by: Sam James <sam@gentoo.org>
=> meson.build: define version

ini.c, tests/baseline_allow_no_value.txt, tests/baseline_call_handler_on_new_section.txt, tests/baseline_disallow_inline_comments.txt, tests/baseline_handler_lineno.txt, tests/baseline_heap.txt, tests/baseline_heap_max_line.txt, tests/baseline_heap_realloc.txt, tests/baseline_heap_realloc_max_line.txt, tests/baseline_multi.txt, tests/baseline_multi_max_line.txt, tests/baseline_single.txt, tests/baseline_stop_on_first_error.txt, tests/multi_line.ini
This is a bug fix that makes inih's behaviour here work as per Python's
ConfigParser, which is what inih behaviour is (loosely) based on.
Thanks @silly2020 for the report. See
https://github.com/benhoyt/inih/issues/120#issuecomment-1181341960
=> Make inline comments work on subsequent lines of multiline values

cpp/INIReader.cpp
MSVC 14.32.3132 throws C4244 when compiling INIReader.cpp.
```
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\algorithm(3031,24): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
1>...\Lib\inih\cpp\INIReader.cpp(72): message : see reference to function template instantiation '_OutIt std::transform<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,int(__cdecl *)(int)>(const _InIt,const _InIt,_OutIt,_Fn)' being compiled
1>        with
1>        [
1>            _OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Elem=char,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<char …
```
=> MSVC throws C4244

meson.build
`start-of-line_comment_prefix` is not a valid identifier in Meson.  It looks like this was partially addressed with `sol_comment_prefix` but didn't make it into actual usage.
=> meson.build: fix start-of-line_comment_prefix variable name

fuzzing/OSS-FUZZ.MD, fuzzing/inihfuzz.c, fuzzing/oss-fuzz.sh
Use [OSS-Fuzz](https://google.github.io/oss-fuzz) for better and continuous fuzzing of [inih](https://github.com/benhoyt/inih)
=> [oss-fuzz] fuzzing support

fuzzing/inihfuzz.c
bug fix: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60878
=> [Fuzzing] fix harness

.github/workflows/cifuzz.yml
using [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) for fuzzing PR.
=> [Fuzzing] using cifuzz for PR

meson.build
Compilers differ on what the default standard is and I had to set C++11 standard as part of the [vcpkg port](https://github.com/microsoft/vcpkg/pull/33001) to get it work on MacOS.
Consequence of #142 
I wasn't sure what standard version to put for C so I left it out.
Also you forgot to bump the version number last release.
=> Specify C++11 std in meson build

cpp/INIReader.h
@benhoyt I am proposing to change variable visibility allowing for full feature inheritance.
=> INIReader: change variable visibility from private to protected

.github/workflows/tests.yml, examples/meson.build, meson.build, tests/meson.build, tests/runtest.sh
Switches tests to use "meson test" instead of a shell script.  This also means that they now fully respect user-specified toolchain (e.g. clang compiler, custom CFLAGS, etc).  Running C++ test is conditional on enabling INIReader support in the build.
```
1/16 test_multi                               OK              0.05s
2/16 test_multi_max_line                      OK              0.04s
3/16 test_single                              OK              0.04s
4/16 test_disallow_inline_comments            OK              0.03s
5/16 test_stop_on_first_error                 OK              0.03s
6/16 test_handler_lineno                      OK              0.02s
7/16 test_heap                                OK              0.06s
8/16 test_string                              OK              0.06s …
```
=> Add meson test driver

ini.c
I confess that the optimization is minimal. But it is free because it does not complicates the code.
With this change, I measured the time spent on the first call of `strlen()`:
```
$ python3 -c 'print(" "*4000 + "name=value")' > long_padding.ini
$ gcc examples/ini_dump.c ini.c -o examples/ini_dump
$ ltrace -T -e strlen ./examples/ini_dump long_padding.ini
ini_dump->strlen("name=value\n")                                     = 11 <0.000147>
```
and without this change (master):
```
ini_dump->strlen("                                "...)              = 4011 <0.001856>
```
The execution time was reduced from `1856 ns` to `147 ns`.
=> Swap rstrip() and lskip() to reduce execution time of strlen()

ini.c
Exclude the `prev_name` variable and the ini_strncpy0() call.
This decreases the program size, the execution time and the stack usage when that flag is off.
But that's barely noticeable. It's more useful for progressive understanding.
When I first came across with this code, I removed (or collapsed) all the `ifdef` blocks to learn the simpler version first.
=> Add preprocessor exclusions when INI_ALLOW_MULTILINE=0

tests/unittest.sh
- **tests: define only once the compiler and flag**
This way you could play with them easily. For example:
- use clang instead gcc
- -Wextra
- -fsanitize=address
- **check CC environ and fallback to gcc**
=> tests: define only once the compiler and flag

tests/baseline_allow_no_value.txt, tests/baseline_call_handler_on_new_section.txt, tests/baseline_disallow_inline_comments.txt, tests/baseline_handler_lineno.txt, tests/baseline_heap.txt, tests/baseline_heap_max_line.txt, tests/baseline_heap_realloc.txt, tests/baseline_heap_realloc_max_line.txt, tests/baseline_multi.txt, tests/baseline_multi_max_line.txt, tests/baseline_single.txt, tests/baseline_stop_on_first_error.txt, tests/long_section.ini, tests/unittest.c
- **test that long sections are truncated**
- **generated .txt executing unittest.sh**
- **expected result**
Should we revert the commit 9f0a1d2199b1a9f0a20003d848918a881a2d91e4 to prevent the CI from failing?
It seems related with a more general issue ( #145 )
=> Test that long sections are truncated

cpp/INIReader.cpp, cpp/INIReader.h, examples/INIReaderExample.cpp, examples/cpptest.txt
This PR adds a SetValue function to the INIReader class, allowing users to modify INI values.
=> Add INIReader Sections and Keys methods

ini.c, tests/baseline_heap_max_line.txt, tests/baseline_heap_realloc_max_line.txt, tests/baseline_heap_string.txt, tests/baseline_multi_max_line.txt, tests/baseline_string.txt
Opening this PR for code review. Thanks @msquire.
=> If a line is longer than INI_MAX_LINE, consume input up to next newline

meson.build
In cross builds, we don't build any C++ code for the build machine.
Fixes Meson warning:
meson.build:106: WARNING: add_languages is missing native:, assuming languages are wanted for both host and build.
=> Require C++ only for the host machine; bump project version to 59

ini.c, tests/baseline_allow_no_value.txt, tests/baseline_call_handler_on_new_section.txt, tests/baseline_disallow_inline_comments.txt, tests/baseline_handler_lineno.txt, tests/baseline_heap.txt, tests/baseline_heap_max_line.txt, tests/baseline_heap_realloc.txt, tests/baseline_heap_realloc_max_line.txt, tests/baseline_multi.txt, tests/baseline_multi_max_line.txt, tests/baseline_single.txt, tests/baseline_stop_on_first_error.txt, tests/name_only_after_error.ini, tests/unittest.c
After an error has occurred the expected behaviour is for parsing to continue unless the `INI_STOP_ON_FIRST_ERROR` option is set. However when `INI_ALLOW_NO_VALUE` is set name only options are currently silently ignored after an error. 
This fixes that minor bug and adds a new test case because it is not exposed by any of the existing ones.
=> Fix bug where name only options are not processed after an error has occurred

ini.c
The default is `INI_MAX_LINE == INI_INITIAL_ALLOC`:
https://github.com/benhoyt/inih/blob/f5f2c6c31e2bf5ea92d678c19c9db834f6c0f840/ini.h#L140-L142
https://github.com/benhoyt/inih/blob/f5f2c6c31e2bf5ea92d678c19c9db834f6c0f840/ini.h#L153-L155
Fixes https://github.com/benhoyt/inih/issues/200#issuecomment-3236279560.
=> Better handle `INI_MAX_LINE <= INI_INITIAL_ALLOC`

cpp/INIReader.cpp, cpp/INIReader.h, examples/INIReaderExampleErrors.cpp, examples/cpptest.sh, examples/cpptesterrors.txt
This is to resolve #202 as per the discussion in that issue.
I also added another C++ example that serves as a test of the functionality in a separate commit (so it can easily be backed out if it isn't wanted).
=> Add INIReader::ParseErrorMessage() to provide brief textual error messages
